# -*- coding: utf-8 -*-
"""Speech_To_Text_Hugging_Face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JR8qivYNHF_22Z_DR7fjFvoaOvyf0cs2

#Speech To Text Hugging Face
"""

!pip install transformers

from transformers import pipeline

import transformers
print(transformers.__version__)

"""###librosa is python package for audio and music analysis
###torch is a ml library used for nlp and computer vision
"""

import librosa
import torch
import IPython.display as display
#Ipython is a interactive command line for python adn it can execute a single line of python code in quickly

from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np

tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

audio, sampling_rate = librosa.load('/v.m4a', sr = 16000)

audio, sampling_rate

display.Audio('/v.m4a', autoplay=True)

input_values=tokenizer(audio, return_tensors='pt').input_values
input_values

logits = model(input_values).logits
logits

predicted_ids = torch.argmax(logits, dim=-1)

transcriptions = tokenizer.batch_decode(predicted_ids)
transcriptions

"""Finally we got the output from a speech to text

"""